version: "3.8"
services:
  multipost-webapp:
    image: registry.cn-hangzhou.aliyuncs.com/famawang-ns/multipost-webapp:latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      cache_from:
        - registry.cn-hangzhou.aliyuncs.com/famawang-ns/multipost-webapp:latest
